[package]
name = "genetic-tsp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
flume = "0.11.0"
lazy_static = "1.4.0"
rand = "0.8.5"
regex = "1.10.2"
